---
abstract: 'Filter YAML through a command-line program'
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Module::Build: '0.28'
  Test::Compile: '0'
  Test::Deep: '0'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-YAML-Filter
requires:
  Data::Partial::Google: '0'
  File::Spec: '0'
  Getopt::Long: '2.36'
  Import::Base: '0'
  Module::Runtime: '0'
  Parse::RecDescent: '0'
  Pod::Usage::Return: '0'
  Regexp::Common: '0'
  Text::Trim: '0'
  YAML: '0'
  boolean: '0'
  perl: '5.010'
resources:
  IRC: irc://irc.perl.org/#yertl
  bugtracker: https://github.com/preaction/App-YAML-Filter/issues
  homepage: https://github.com/preaction/App-YAML-Filter
  repository: https://github.com/preaction/App-YAML-Filter.git
version: '0.015'
x_authority: cpan:PREACTION
